name: pv_output_prediction

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4.1.6

    - name: Set up Python test environment
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.9

    - name: Run unittest
      run: python -m unittest tests.test_optimize_model

    - name: Run with test data
      run: bash tests/test.sh
